DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS items;

CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE items (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  item_name TEXT NOT NULL,
  ingredient_one TEXT NOT NULL,
  ingredient_two TEXT,
  ingredient_three TEXT,
  ingredient_four TEXT,
  ingredient_five TEXT,
  ingredient_six TEXT,
  sell_price NUMERIC NOT NULL,
  item_type TEXT NOT NULL,
  tag_one TEXT,
  tag_two TEXT,
  tag_three TEXT
);